steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/oxygen-fastapi-app', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/oxygen-fastapi-app']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'oxygen-fastapi-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/oxygen-fastapi-app'
      - '--platform'
      - 'managed'
      - '--region'
      - 'asia-south1'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'DB_USER=$_DB_USER'
      - '--set-env-vars'
      - 'DB_PASSWORD=$_DB_PASSWORD'
      - '--set-env-vars'
      - 'DB_HOST=$_DB_HOST'
      - '--set-env-vars'
      - 'DB_NAME=$_DB_NAME'
      - '--set-env-vars'
      - 'DB_PORT=5432'
      - '--set-env-vars'
      - 'CLOUD_SQL_CONNECTION_NAME=$_CLOUD_SQL_CONNECTION_NAME'
      - '--vpc-connector'
      - 'oxygen-vpc-connector'
      - '--cpu=2'
      - '--memory=2Gi'

substitutions:
  _DB_USER: fastapi-db-user
  _DB_NAME: fastapi-db-name
  _DB_HOST: 10.231.0.3   # Private IP for Cloud Run (use public IP for local dev)
  _DB_PASSWORD: fastapiDB@12
  _CLOUD_SQL_CONNECTION_NAME: master-shell-468709-v8:asia-south1:fastapi-db

options:
  logging: CLOUD_LOGGING_ONLY
